version: '3.9'

services:
  mysql:
    container_name: todolist_mysql
    restart: always
    image: mysql:latest
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASSWORD}
    volumes:
      - datavolume:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  testmysql:
    container_name: todolist_mysql_test
    restart: always
    image: mysql:latest
    ports: 
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: testroot
      MYSQL_USER: testuser
      MYSQL_PASS: testuserpwd
    volumes:
      - testdatavolume:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  datavolume:
  testdatavolume: